#!/usr/bin/env bash

( \
	cat esm/before.js; \
	./node_modules/browserify/bin/cmd.js --entry esm/entrypoint.js; \
	cat esm/after.js; \
) | cat | ./node_modules/terser/bin/terser \
	--compress \
	--mangle \
	> dist/js-yaml.esm.js
